apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter-svc
  namespace: react-app
  labels:
    app: nginx-exporter
spec:
  selector:
    app: mi-chart
  ports:
    - protocol: TCP
      port: 9113
      targetPort: 9113
  type: ClusterIP
